/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router,
  // browserHistory,
  hashHistory,
} from 'react-router';

// 路由配置规则参考： https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#configuration-with-plain-routes
// 一下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
import Evolution from './pages/Evolution';
import EntityList from './pages/EntityList';
import CreateEntity from './pages/CreateEntity';
import CreateProject from './pages/CreateProject';
import ProjectList from './pages/ProjectList';
import HeaderAsideFooterResponsiveLayout from './layouts/HeaderAsideFooterResponsiveLayout';
import HeaderFooterLayout from './layouts/HeaderFooterLayout';
import Dashboard from './pages/Dashboard';
import UserList from './pages/UserList';
import CreateUser from './pages/CreateUser';
import EditPassword from './pages/EditPassword';
import BasicSetting from './pages/BasicSetting';
import NavigationSetting from './pages/NavigationSetting';
import BlankLayout from './layouts/BlankLayout';
import Login from './pages/Login';
import NotFound from './pages/NotFound';
const autoGeneratedRoutes = [{
  path: '/evolution',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Evolution
  }
}, {
  path: '/entity',
  childRoutes: [{
    path: 'list',
    childRoutes: [],
    component: EntityList
  }, {
    path: 'create',
    childRoutes: [],
    component: CreateEntity
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: EntityList
  }
}, {
  path: '/project',
  childRoutes: [{
    path: 'list',
    childRoutes: [],
    component: ProjectList
  }, {
    path: 'create',
    childRoutes: [],
    component: CreateProject
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ProjectList
  }
}, {
  path: '/login',
  childRoutes: [],
  component: BlankLayout,
  indexRoute: {
    component: Login
  }
}, {
  path: '/dashboard',
  childRoutes: [],
  component: HeaderFooterLayout,
  indexRoute: {
    component: Dashboard
  }
}, {
  path: '/setting',
  childRoutes: [{
    path: 'basic',
    childRoutes: [],
    component: BasicSetting
  }, {
    path: 'navigation',
    childRoutes: [],
    component: NavigationSetting
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: BasicSetting
  }
}, {
  path: '/user',
  childRoutes: [{
    path: 'list',
    childRoutes: [],
    component: UserList
  }, {
    path: 'create',
    childRoutes: [],
    component: CreateUser
  }, {
    path: 'pwd',
    childRoutes: [],
    component: EditPassword
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: UserList
  }
}, {
  path: '/',
  childRoutes: [{
    path: '*',
    childRoutes: [],
    component: NotFound
  }],
  component: BlankLayout,
  indexRoute: {
    component: Login
  }
}];
// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
